permissions:
  contents: read
name: Linter & format check

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx --yes oxlint@1.7.0 --deny-warnings --ignore-pattern=.astro

  prettier-check:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        run: npm install -g pnpm@10.13.1
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run prettier check
        run: pnpm exec prettier --check "**/*.{js,jsx,ts,tsx,json,css,md}"
