name: Linter

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx --yes oxlint@1.7.0 --deny-warnings
