env:
  DIRECTORY: apps/tabisphere/dist
  PROJECT_NAME: tabisphere

name: "Tabisphere: Release"

on:
  workflow_dispatch: null

jobs:
  Version:
    outputs:
      created: ${{ steps.version.outputs.created }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install dependencies from monorepo root
        run: pnpm install --frozen-lockfile

      - name: Build Tabisphere app from monorepo root
        run: pnpm run build

      - name: Create tag if necessary
        id: version
        uses: fregante/daily-version-action@v2

      - name: Debug: Show version outputs
        run: |
          echo "Created: '${{ steps.version.outputs.created }}'"
          echo "Version: '${{ steps.version.outputs.version }}'"

      - name: Update manifest.json with version
        if: steps.version.outputs.created == 'true'
        run: npx dot-json@1 "$DIRECTORY/manifest.json" version "${{ steps.version.outputs.version }}"

      - name: Upload built dist folder as artifact
        if: steps.version.outputs.created == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-dist
          path: ${{ env.DIRECTORY }}

      - name: Create GitHub release
        if: steps.version.outputs.created == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ env.DIRECTORY }}
        run: |
          FILENAME="${PROJECT_NAME}-${{ steps.version.outputs.version }}.zip"
          zip -r "$FILENAME" ./*
          gh release create "${{ steps.version.outputs.version }}" --generate-notes "$FILENAME"

  Chrome:
    if: needs.Version.outputs.created == 'true'
    needs: Version
    name: Submit (Chrome)
    environment: Chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: tabisphere-dist
          path: artifact

      - run: npx chrome-webstore-upload-cli@3
        working-directory: artifact
        env:
          EXTENSION_ID: ${{ secrets.TABISPHERE_EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
